package by.aistexped.documentgenerator;

public enum Property {
    TEMPLATE_NUMBER_LABEL,
    CONTRACT_PATH,
    CONTRACT_TITLE_TEMPLATE,
    NEXT_CONTRACT_NUMBER,
    CONTRACT_NUMBER_PREFIX,
    CONTRACT_NUMBER_POSTFIX,
    ORDER_PATH,
    ORDER_TITLE_TEMPLATE,
    NEXT_ORDER_NUMBER,
    ORDER_NUMBER_PREFIX,
    ORDER_NUMBER_POSTFIX,
    TEMPLATE_CUSTOMER_LABEL,
    CUSTOMER_LIST,
    DEFAULT_SAVE_DIRECTORY
}
